name: Daily Python Script

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:  # allows manual runs from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEETS_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SHEETS_SERVICE_ACCOUNT }}
      GOOGLE_SHEETS_URL_KEY: ${{ secrets.GOOGLE_SHEETS_URL_KEY }}
      PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
      STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies with uv
        run: |
          uv install  # this will install packages from uv.lock/uv.yaml

      - name: Run script
        run: python pipeline.py
